services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestor_gastos

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db