upstream backend_servers {
    # Usamos la directiva 'resolve' de Docker para actualizar las IPs de las réplicas en tiempo real
    server backend:3000;
}

upstream frontend_servers {
    server frontend:80;
}

server {
    listen 80;

    # Habilitar logs detallados para la demostración
    access_log /var/log/nginx/access.log;

    # 1. Rutas para el Frontend
    location / {
        proxy_pass http://frontend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # 👈 CABECERAS EXTRA PARA LA EVALUACIÓN
        add_header X-Upstream-Address $upstream_addr always;
        add_header X-Balancing-Status "Swarm Routed" always;
    }

    # 2. Rutas para la API del Backend
    location /api/ {
        proxy_pass http://backend_servers/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # 🔥 Esto le permite al Backend saber la IP original del cliente y no la de Nginx
        proxy_set_header X-Forwarded-Proto $scheme;

        # 👈 CABECERAS EXTRA PARA LA EVALUACIÓN (Muestra qué IP interna de réplica respondió)
        add_header X-Upstream-Backend-Addr $upstream_addr always;
    }
}